backend:
  name: git-gateway
  branch: main

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: "sekce"
    label: "Sekce stránky"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Název sekce", name: "title", widget: "string" }
      - { label: "Obsah (HTML nebo text)", name: "body", widget: "markdown" }
